language: node_js
node_js:
  - '8'
cache: npm
script:
  - npm test
after_success:
  - npm run build
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-east-2"
  app: "BeanTest"
  env: "BeanTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-124532820514"
  on:
    branch: master